<a href="https://colab.research.google.com/github/tummalapallimurali/Algorithms/blob/main/ART1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 3 (software mini-project)

Create a file with the first six letters (smaller font – 15 inputs) from project 4.5 on page 215.  These are letters A, B, C, D, E, and J.  Use an encoding with the dots = 0 and the # = 1.  This is a file with 6 pure letters.  Take these six exemplars and create five versions of each exemplar by randomly changing only one bit each.  You now have a new dataset of 30 patterns and six classes. This is a noisier file of patterns.


Use the ART1 paradigm to do this problem.  Experiment training with the file with 6 pure letters for five different values of the vigilance parameter and three different values of number of output neurons (this must be set to at least 6 – one for each class).  Then test the trained networks on your training file and on the noisier file.  How did each do?  Then, pick a network that did not do that well, and try complement coding.  Did this change the performance?  Then, pick a network that did pretty well and reorder the training set.  Train again, and see if any differences occurred.  You might try sorting the training patterns from most to least dense (this is supposed to help).  Summarize your results in all these experiments in a table format and discuss your findings.


In [ ]:
import numpy as np
#Tesing
# Step 1: Create the pure letters dataset
input_patterns = {
    "A": [0, 1, 0 ,1, 0 ,1 ,1, 1,1 ,1, 0 ,1 ,1, 0 ,1],
    "B" : [1,1, 0, 1, 0, 1, 1,1, 0,1,0,1,1,1, 0],
    "C" :  [1,1, 1, 1, 0, 0,1,0,0,1,0,0,1, 1,1 ],
    "D" : [1, 1, 0, 1, 0, 1,1, 0, 1,1, 0, 1, 1, 1, 0 ],
    "E" : [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1],
    "J" : [0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0]
}


# Step 2: Create noisy versions of each letter
noisy_input_patterns = {}
for letter, pattern in input_patterns.items():
    for i in range(1, 6):
        noisy_pattern = pattern.copy()
        noisy_pattern[np.random.randint(0, len(noisy_pattern))] = 1 - noisy_pattern[np.random.randint(0, len(noisy_pattern))]
        noisy_input_patterns[f"{letter}{i}"] = noisy_pattern

In [ ]:
print(noisy_input_patterns)

{'A1': [0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1], 'A2': [0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1], 'A3': [0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1], 'A4': [0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1], 'A5': [1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1], 'B1': [0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0], 'B2': [1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0], 'B3': [1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0], 'B4': [1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0], 'B5': [1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0], 'C1': [0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1], 'C2': [1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1], 'C3': [1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1], 'C4': [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1], 'C5': [1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1], 'D1': [1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0], 'D2': [1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0], 'D3': [1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0], 'D4': [1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,

Notes: Art1 algorithm(Model developed and tested in numpy and python 3.12) , plese clear outputs and re-run.
The following art1 model is implemented in python3. The model is implemented in a class called ART1. The class has the following methods:
1. __init__: This is the constructor of the class. It initializes the parameters of the model.
2. train: This method trains the model on the input data.
3. predict: This method predicts the cluster of the input data. The method returns the cluster number of the input data. The method also returns the vigilance of the model. The vigilance is the minimum similarity between the input data and the cluster prototype.
4. The objective of predict method is to identify the cluster of the input data.
5. The predict method uses the following formula to calculate the similarity between the input data and the cluster prototype:


In [ ]:
import numpy as np

class ART1:
    def __init__(self, num_comp, clusters, vigilance, L):
        self.num_comp = num_comp
        self.clusters = clusters
        self.vigilance = vigilance
        self.L = L
        self.tops = np.ones((clusters, num_comp))
        self.bottoms = np.ones((num_comp, clusters)) / (1 + num_comp)
        self.assignments = np.zeros(clusters, dtype=int)  # Cluster assignments

    # Train the model with the input patterns
    def train(self, input_patterns):
        for i, (pattern_name, pattern) in enumerate(input_patterns.items()):
            pattern = np.array(pattern)
            net = np.dot(pattern, self.bottoms)
            max_net = np.argmax(net)
            vigilance_test = np.dot(pattern, self.tops[max_net]) / np.dot(pattern, pattern)
            if vigilance_test >= self.vigilance:
                self.tops[max_net] = pattern * self.tops[max_net]
                self.bottoms[:, max_net] = (self.L / (self.L - 1 + np.sum(self.tops[max_net]))) * pattern

            else:
                net[max_net] = -1
                max_net = np.argmax(net)
                vigilance_test = np.dot(pattern, self.tops[max_net]) / np.dot(pattern, pattern)
                if vigilance_test >= self.vigilance:
                    self.tops[max_net] = pattern * self.tops[max_net]
                    self.bottoms[:, max_net] = (self.L / (self.L - 1 + np.sum(self.tops[max_net]))) * pattern

        return self.assignments

# Predict the cluster of the input patterns
    def predict(self, input_patterns):
        data = []
        for i, (pattern_name, pattern) in enumerate(input_patterns.items()):
            pattern = np.array(pattern)
            net = np.dot(pattern, self.bottoms)
            max_net = np.argmax(net)
            vigilance_test = np.dot(pattern, self.tops[max_net]) / np.dot(pattern, pattern)
            if vigilance_test >= self.vigilance:
                data.append([pattern_name, max_net])
            else:
                net[max_net] = -1
                max_net = np.argmax(net)
                vigilance_test = np.dot(pattern, self.tops[max_net]) / np.dot(pattern, pattern)
                if vigilance_test >= self.vigilance:
                    data.append([pattern_name, max_net])
                else:
                    data.append([pattern_name, "Not assigned"])
        return data


    # print weights
    def print_weights(self):
        print(f"Top Down Weights: {self.tops}")
        print(f"Bottom Up Weights: {self.bottoms}")




In [ ]:
vigilance = [0.2, 0.3, 0.4, 0.5, 0.6]

for v in vigilance:
    art1 = ART1(15, 6, v, 2)
    art1.train(input_patterns)
    data = art1.predict(input_patterns)
    # create a dataframe for each vigilance value and print the cluster number and pattern names
    import pandas as pd
    df = pd.DataFrame(data, columns=["Pattern Name", "Cluster Number"])
    print(f"Vigilance: {v}")
    print(df.groupby("Cluster Number")["Pattern Name"].apply(tuple).reset_index())
    print("\n\n")

Vigilance: 0.2
   Cluster Number     Pattern Name
0               0  (A, B, C, D, E)
1               1             (J,)



Vigilance: 0.3
   Cluster Number     Pattern Name
0               0  (A, B, C, D, E)
1               1             (J,)



Vigilance: 0.4
   Cluster Number     Pattern Name
0               0  (A, B, C, D, E)
1               1             (J,)



Vigilance: 0.5
  Cluster Number  Pattern Name
0              0  (A, B, C, D)
1              1          (J,)
2   Not assigned          (E,)



Vigilance: 0.6
  Cluster Number Pattern Name
0              0    (A, B, D)
1              1       (C, E)
2   Not assigned         (J,)





Summary:
1. With vigilance parameter 0.2, 0.3 and 0.4 the network was able to cluster patterns A, B, C and D in cluster 0 and
J in cluster 1.
2. using vigilance parameter 0.5 and 0.6 , it couldnt cluster letter J. Therefore we can use vigilance parameter between 0.2 - 0.3 to fit the patterns.
3. when Art1 network is tested on  noisy patterns when predicted letters A1 , A2, A3, A4, A5 .....E5 are predicted in Cluster 0 and J1 - J5 are clustered in 1.
4. Updadated weights and printed below. Node 0 and Node 1 weights are updated.




In [ ]:

vigilance = [0.2, 0.3, 0.4, 0.5, 0.6]

for v in vigilance:
    art1 = ART1(15, 6, v, 2)
    art1.train(input_patterns)
    data = art1.predict(noisy_input_patterns)
    # create a dataframe for each vigilance value and print the cluster number and pattern names
    import pandas as pd
    df = pd.DataFrame(data, columns=["Pattern Name", "Cluster Number"])
    print(f"Vigilance: {v}")
    print(df.groupby("Cluster Number")["Pattern Name"].apply(tuple).reset_index())
    print("\n\n")


Vigilance: 0.2
   Cluster Number                                       Pattern Name
0               0  (A1, A2, A3, A4, A5, B1, B2, B3, B4, B5, C1, C...
1               1                               (J1, J2, J3, J4, J5)



Vigilance: 0.3
   Cluster Number                                       Pattern Name
0               0  (A1, A2, A3, A4, A5, B1, B2, B3, B4, B5, C1, C...
1               1                               (J1, J2, J3, J4, J5)



Vigilance: 0.4
   Cluster Number                                       Pattern Name
0               0  (A1, A2, A3, A4, A5, B1, B2, B3, B4, B5, C1, C...
1               1                               (J1, J2, J3, J4, J5)



Vigilance: 0.5
  Cluster Number                                       Pattern Name
0              0  (A1, B1, B3, B4, B5, C1, C2, C3, C4, C5, D2, D...
1              1                               (J1, J2, J3, J4, J5)
2   Not assigned           (A2, A3, A4, A5, B2, D1, D4, D5, E1, E4)



Vigilance: 0.6
  Cluster Number    

In [ ]:
# print the weights
art1.print_weights()


Top Down Weights: [[0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Bottom Up Weights: [[0.25   0.2    0.0625 0.0625 0.0625 0.0625]
 [0.25   0.2    0.0625 0.0625 0.0625 0.0625]
 [0.     0.2    0.0625 0.0625 0.0625 0.0625]
 [0.25   0.2    0.0625 0.0625 0.0625 0.0625]
 [0.     0.     0.0625 0.0625 0.0625 0.0625]
 [0.25   0.     0.0625 0.0625 0.0625 0.0625]
 [0.25   0.2    0.0625 0.0625 0.0625 0.0625]
 [0.     0.2    0.0625 0.0625 0.0625 0.0625]
 [0.25   0.2    0.0625 0.0625 0.0625 0.0625]
 [0.25   0.2    0.0625 0.0625 0.0625 0.0625]
 [0.     0.     0.0625 0.0625 0.0625 0.0625]
 [0.25   0.     0.0625 0.0625 0.0625 0.0625]
 [0.25   0.2    0.0625 0.0625 0.0625 0.0625]
 [0.25   0.2    0.0625 0.0625 0.0625 0.0625]
 [0.     0.2    0.0625 0.0625 0.0625 0.0625]